[workspace]
resolver = "3"
members = ["parser", "monitor", "cmd", "busd", "metrics"]

[workspace.dependencies]
# project crates:
samsung_nasa_busd = { path = "busd" }
samsung_nasa_metrics = { path = "metrics" }
samsung_nasa_monitor = { path = "monitor" }
samsung_nasa_parser = { path = "parser" }

# external deps:
heapless = "0.8"
serialport = { version = "4.7", default-features = false }
structopt = "0.3"
