[workspace]
resolver = "3"
members = [
    "busd",
    "cmd",
    "metrics",
    "monitor",
    "parser",
    "client",
]

[workspace.dependencies]
# project crates:
samsunghvac-busd = { path = "busd" }
samsunghvac-metrics = { path = "metrics" }
samsunghvac-monitor = { path = "monitor" }
samsunghvac-parser = { path = "parser" }

# external deps:
heapless = "0.8"
serialport = { version = "4.7", default-features = false }
structopt = "0.3"
