[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-ld"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-ld"
# rustflags = [
#     "-C", "link-arg=-fuse-ld=mold",
#     "-C", "link-arg=--target=aarch64-unknown-linux-musl",
# ]
