[package]
name = "samsung_nasa_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0", default-features = false, features = ["debug", "display"] }
heapless = "0.8"
thiserror = "2.0"
ux = "0.1.6"
