[package]
name = "samsunghvac-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0", default-features = false, features = ["debug", "display", "try_from", "into"] }
heapless = { workspace = true }
log = { workspace = true }
thiserror = "2.0"
ux = "0.1"
