[package]
name = "samsunghvac-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
samsunghvac-busd = { workspace = true }
samsunghvac-parser = { workspace = true }
serialport = { workspace = true }
structopt = { workspace = true }
