[package]
name = "samsung_nasa_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
samsung_nasa_busd = { workspace = true }
samsung_nasa_parser = { workspace = true }
serialport = { workspace = true }
structopt = { workspace = true }
